# Generated by Django 4.2.7 on 2023-11-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_test_app", "0002_alter_testmodel_foreign_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReverseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_test_app.testmodel",
                    ),
                ),
            ],
        ),
    ]
