# Generated by Django 4.2.7 on 2023-11-25 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RelatedManyToManyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RelatedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RelatedOneToOneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_field", models.CharField(max_length=255)),
                ("text_field", models.TextField()),
                ("date_field", models.DateField(auto_now_add=True)),
                ("date_time_field", models.DateTimeField(auto_now_add=True)),
                ("decimal_field", models.DecimalField(decimal_places=2, max_digits=10)),
                ("integer_field", models.IntegerField()),
                ("float_field", models.FloatField()),
                (
                    "foreign_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_test_app.relatedmodel",
                    ),
                ),
                (
                    "many_to_many_field",
                    models.ManyToManyField(to="django_test_app.relatedmanytomanymodel"),
                ),
                (
                    "one_to_one_field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_test_app.relatedonetoonemodel",
                    ),
                ),
            ],
        ),
    ]
