# Generated by Django 4.2.7 on 2023-11-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="foreign_key",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_test_app.relatedmodel",
            ),
        ),
        migrations.AlterField(
            model_name="testmodel",
            name="one_to_one_field",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_test_app.relatedonetoonemodel",
            ),
        ),
    ]
